"""Add APIKeys table

Revision ID: 23568d0fd535
Revises: 
Create Date: 2024-11-16 23:10:27.079572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23568d0fd535'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('items_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_groups_name'), 'items_groups', ['name'], unique=True)
    op.create_table('items_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_lines_name'), 'items_lines', ['name'], unique=True)
    op.create_table('items_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_types_name'), 'items_types', ['name'], unique=True)
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('name', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_code'), 'locations', ['code'], unique=False)
    op.create_index(op.f('ix_locations_created_at'), 'locations', ['created_at'], unique=False)
    op.create_index(op.f('ix_locations_id'), 'locations', ['id'], unique=False)
    op.create_index(op.f('ix_locations_name'), 'locations', ['name'], unique=False)
    op.create_index(op.f('ix_locations_updated_at'), 'locations', ['updated_at'], unique=False)
    op.create_index(op.f('ix_locations_warehouse_id'), 'locations', ['warehouse_id'], unique=False)
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('address_extra', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('province', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('contact_name', sa.String(), nullable=True),
    sa.Column('phonenumber', sa.String(), nullable=True),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_code'), 'suppliers', ['code'], unique=True)
    op.create_index(op.f('ix_suppliers_id'), 'suppliers', ['id'], unique=False)
    op.create_table('transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('transfer_from', sa.Integer(), nullable=True),
    sa.Column('transfer_to', sa.Integer(), nullable=False),
    sa.Column('transfer_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('items', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transfers_created_at'), 'transfers', ['created_at'], unique=False)
    op.create_index(op.f('ix_transfers_id'), 'transfers', ['id'], unique=False)
    op.create_index(op.f('ix_transfers_items'), 'transfers', ['items'], unique=False)
    op.create_index(op.f('ix_transfers_reference'), 'transfers', ['reference'], unique=False)
    op.create_index(op.f('ix_transfers_transfer_status'), 'transfers', ['transfer_status'], unique=False)
    op.create_index(op.f('ix_transfers_updated_at'), 'transfers', ['updated_at'], unique=False)
    op.create_table('warehouses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('zip', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('province', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('contact', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouses_address'), 'warehouses', ['address'], unique=False)
    op.create_index(op.f('ix_warehouses_city'), 'warehouses', ['city'], unique=False)
    op.create_index(op.f('ix_warehouses_code'), 'warehouses', ['code'], unique=False)
    op.create_index(op.f('ix_warehouses_contact'), 'warehouses', ['contact'], unique=False)
    op.create_index(op.f('ix_warehouses_country'), 'warehouses', ['country'], unique=False)
    op.create_index(op.f('ix_warehouses_created_at'), 'warehouses', ['created_at'], unique=False)
    op.create_index(op.f('ix_warehouses_id'), 'warehouses', ['id'], unique=False)
    op.create_index(op.f('ix_warehouses_name'), 'warehouses', ['name'], unique=False)
    op.create_index(op.f('ix_warehouses_province'), 'warehouses', ['province'], unique=False)
    op.create_index(op.f('ix_warehouses_updated_at'), 'warehouses', ['updated_at'], unique=False)
    op.create_index(op.f('ix_warehouses_zip'), 'warehouses', ['zip'], unique=False)
    op.create_table('items',
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('short_description', sa.String(), nullable=True),
    sa.Column('upc_code', sa.String(), nullable=True),
    sa.Column('model_number', sa.String(), nullable=True),
    sa.Column('commodity_code', sa.String(), nullable=True),
    sa.Column('item_line', sa.Integer(), nullable=True),
    sa.Column('item_group', sa.Integer(), nullable=True),
    sa.Column('item_type', sa.Integer(), nullable=True),
    sa.Column('unit_purchase_quantity', sa.Integer(), nullable=True),
    sa.Column('unit_order_quantity', sa.Integer(), nullable=True),
    sa.Column('pack_order_quantity', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('supplier_code', sa.String(), nullable=True),
    sa.Column('supplier_part_number', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_group'], ['items_groups.id'], ),
    sa.ForeignKeyConstraint(['item_line'], ['items_lines.id'], ),
    sa.ForeignKeyConstraint(['item_type'], ['items_types.id'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_items_code'), 'items', ['code'], unique=True)
    op.create_index(op.f('ix_items_uid'), 'items', ['uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_uid'), table_name='items')
    op.drop_index(op.f('ix_items_code'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_warehouses_zip'), table_name='warehouses')
    op.drop_index(op.f('ix_warehouses_updated_at'), table_name='warehouses')
    op.drop_index(op.f('ix_warehouses_province'), table_name='warehouses')
    op.drop_index(op.f('ix_warehouses_name'), table_name='warehouses')
    op.drop_index(op.f('ix_warehouses_id'), table_name='warehouses')
    op.drop_index(op.f('ix_warehouses_created_at'), table_name='warehouses')
    op.drop_index(op.f('ix_warehouses_country'), table_name='warehouses')
    op.drop_index(op.f('ix_warehouses_contact'), table_name='warehouses')
    op.drop_index(op.f('ix_warehouses_code'), table_name='warehouses')
    op.drop_index(op.f('ix_warehouses_city'), table_name='warehouses')
    op.drop_index(op.f('ix_warehouses_address'), table_name='warehouses')
    op.drop_table('warehouses')
    op.drop_index(op.f('ix_transfers_updated_at'), table_name='transfers')
    op.drop_index(op.f('ix_transfers_transfer_status'), table_name='transfers')
    op.drop_index(op.f('ix_transfers_reference'), table_name='transfers')
    op.drop_index(op.f('ix_transfers_items'), table_name='transfers')
    op.drop_index(op.f('ix_transfers_id'), table_name='transfers')
    op.drop_index(op.f('ix_transfers_created_at'), table_name='transfers')
    op.drop_table('transfers')
    op.drop_index(op.f('ix_suppliers_id'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_code'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_locations_warehouse_id'), table_name='locations')
    op.drop_index(op.f('ix_locations_updated_at'), table_name='locations')
    op.drop_index(op.f('ix_locations_name'), table_name='locations')
    op.drop_index(op.f('ix_locations_id'), table_name='locations')
    op.drop_index(op.f('ix_locations_created_at'), table_name='locations')
    op.drop_index(op.f('ix_locations_code'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_items_types_name'), table_name='items_types')
    op.drop_table('items_types')
    op.drop_index(op.f('ix_items_lines_name'), table_name='items_lines')
    op.drop_table('items_lines')
    op.drop_index(op.f('ix_items_groups_name'), table_name='items_groups')
    op.drop_table('items_groups')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
