"""added clients, transfers and inventories

Revision ID: 8b303dc3fe3f
Revises: 790d11f0ffb7
Create Date: 2024-11-21 23:23:29.365345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b303dc3fe3f'
down_revision: Union[str, None] = '790d11f0ffb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'items', 'suppliers', ['supplier_id'], ['id'])
    op.drop_index('ix_transfers_reference', table_name='transfers')
    op.create_index(op.f('ix_transfers_reference'), 'transfers', ['reference'], unique=True)
    op.drop_index('ix_warehouses_created_at', table_name='warehouses')
    op.drop_index('ix_warehouses_updated_at', table_name='warehouses')
    op.drop_index('ix_warehouses_code', table_name='warehouses')
    op.create_index(op.f('ix_warehouses_code'), 'warehouses', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_warehouses_code'), table_name='warehouses')
    op.create_index('ix_warehouses_code', 'warehouses', ['code'], unique=False)
    op.create_index('ix_warehouses_updated_at', 'warehouses', ['updated_at'], unique=False)
    op.create_index('ix_warehouses_created_at', 'warehouses', ['created_at'], unique=False)
    op.drop_index(op.f('ix_transfers_reference'), table_name='transfers')
    op.create_index('ix_transfers_reference', 'transfers', ['reference'], unique=False)
    op.drop_constraint(None, 'items', type_='foreignkey')
    # ### end Alembic commands ###
